environment:
  scoop: C:\projects\scoop
  scoop_home: C:\projects\scoop\apps\scoop\current

branches:
  except:
    - gh-pages

skip_commits:
  files:
    - '**/*.md'
    - '.vscode/**/*'

init:
  - ps: >-
      (Get-PsProvider 'FileSystem').Home = 'c:\projects\'
      iex (New-Object System.Net.Webclient).DownloadString('https://get.scoop.sh')
      Install-Module -Name Pester -Repository PSGallery -Force

build: off

test_script:
  - ps: >-
      $result = Invoke-Pester -OutputFile TestResults.xml -OutputFormat NUnitXML -PassThru
      $where = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      $what = (Resolve-Path ./TestResults.xml)
      (New-Object System.Net.Webclient).UploadFile($where, $what)
      exit $result.failedcount

