environment:
  scoop: C:\projects\scoop
  scoop_home: C:\projects\scoop\apps\scoop\current

branches:
  except:
    - gh-pages

skip_commits:
  files:
    - '**/*.md'
    - '.vscode/**/*'

init:
  - ps: |
      (Get-PsProvider 'FileSystem').Home = 'c:\projects\'
      iex (New-Object System.Net.Webclient).DownloadString('https://get.scoop.sh')
      Install-Module -Name Pester -Repository PSGallery -Force

build: off

artifacts:
  - path: C:\TestResults.xml

test_script:
  - ps: |
      $result = Invoke-Pester -OutputFile 'C:\TestResults.xml' -OutputFormat NUnitXML -PassThru -EnableExit

